GET http://localhost:3000/api/v1/hub_user/

###

GET http://localhost:3000/api/v1/hub_user/   id's go at the end

###

POST http://localhost:3000/api/v1/hub_user/
Content-Type: application/json

{
    "userName": "Tirth Patel",
    "platform": "Steam",
    "password": "12345678"

}

###

DELETE http://localhost:3000/api/v1/hub_user/ 

###

PATCH  http://localhost:3000/api/v1/hub_user/

Content-Type: application/json
{
    "userName": "FalconDude82",
    "platform": "Xbox",
    "password": "microshit"
}